---
title: "p8105_hw2_ng3005"
author: "Nelson Gaillard"
date: "2025-09-28"
output: github_document
---

```{r}
library(tidyverse)
```

### Problem 1

First, let's clean the data in pols-month.csv

```{r}
pols_df =
  read_csv("data/pols-month.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(
    mon, into = c("year", "month", "day")
  ) |>
  mutate(month = case_match(
    month,
    "01" ~ "January", 
    "02" ~ "February",
    "03" ~ "March",
    "04" ~ "April", 
    "05" ~ "May",
    "06" ~ "June",
    "07" ~ "July", 
    "08" ~ "August",
    "09" ~ "September",
    "10" ~ "October",
    "11" ~ "November",
    "12" ~ "December"
  )) |>
  mutate(year = as.integer(year)) |>
  mutate(president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem"
  )) |>
  select(-c(prez_gop, prez_dem, day))
```

Next, let's clean the data in snp.csv

```{r}
snp_df =
  read_csv("data/snp.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(
    date, into = c("month", "day", "year")
  ) |>
  mutate(month = case_match(
    month,
    "1" ~ "January", 
    "2" ~ "February",
    "3" ~ "March",
    "4" ~ "April", 
    "5" ~ "May",
    "6" ~ "June",
    "7" ~ "July", 
    "8" ~ "August",
    "9" ~ "September",
    "10" ~ "October",
    "11" ~ "November",
    "12" ~ "December"
  )) |>
  mutate(year = as.integer(year)) |>
  mutate(year = ifelse(year > 50, 1900 + year, 2000 + year)) |>
  select(-day) |>
  relocate(year, month, close)
```

Third, let's clean the unemployment.csv data

```{r}
unemployment_df =
  read_csv("data/unemployment.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_pct"
  ) |>
  mutate(year = as.integer(year))
```

Finally, we can merge these datasets into one!

```{r}
fivethirtyeight_df =
  left_join(pols_df, snp_df, unemployment_df, by = c("year", "month"))
```


